### ISSUE TITLE
PortAudio does not help create virtual device

### ISSUE THREAD

**Issue by ankitkumar93** [technited/AudioRouter#8]
The callback buffer for input is const, so cannot edit it. There is no API for creating a virtual device.
The main question is:
Why do we need port audio?
Maybe write audio from speakers to file?
Maybe combine audio from speakers and mic and write to file?

**Comment by vasumahesh1** [comment]
Apart from direct virtualization of hardware there wont be any way for Apps like Skype, Discord to route audio to us.

**Comment by ankitkumar93** [comment]
Good point. Lets move away from port audio and focus on the virtualization using alsa/win32. I think for now lets just focus on alsa and getting it up for linux. Windows can wait.
